apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: devmalik715/order-service:latest
        ports:
        - containerPort: 3000
