apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: devmalik715/payment-service:latest
        ports:
        - containerPort: 3000
