apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: devmalik715/product-service:latest
        ports:
        - containerPort: 3000
