apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
      - name: ui-service
        image: devmalik715/ui-service:latest
        ports:
        - containerPort: 3000
